# Generated by Django 4.2.23 on 2026-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_candidate_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='justification',
            field=models.TextField(blank=True, help_text='Business reason for opening this position', null=True, verbose_name='Justification'),
        ),
    ]
