# Generated by Django 4.2.23 on 2026-05-13 10:12
# Modified to handle pre-existing tables/columns on live database.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_candidate_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0002_add_justification_to_recruitment'),
    ]

    operations = [
        # ── Tables that ALREADY EXIST in production ──────────────────────────
        # We update only Django's internal state (no DDL executed).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='JobEmailTemplate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('selection_subject', models.CharField(max_length=200)),
                        ('selection_body', models.TextField()),
                        ('rejection_subject', models.CharField(max_length=200)),
                        ('rejection_body', models.TextField()),
                        ('is_default', models.BooleanField(default=False)),
                    ],
                    options={'ordering': ['id']},
                ),
                migrations.CreateModel(
                    name='JobApplication',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('email', models.EmailField(max_length=254)),
                        ('phone', models.CharField(blank=True, max_length=30, null=True)),
                        ('country', models.CharField(blank=True, max_length=100, null=True)),
                        ('experience', models.TextField(blank=True, null=True)),
                        ('why_apply', models.TextField(blank=True, null=True)),
                        ('resume_path', models.CharField(blank=True, max_length=500, null=True)),
                        ('status', models.CharField(choices=[('applied', 'Applied'), ('screened', 'Screened'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                        ('score', models.IntegerField(blank=True, null=True)),
                        ('ai_reason', models.TextField(blank=True, null=True)),
                        ('hr_override', models.BooleanField(default=False)),
                        ('excluded_by_second_filter', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='recruitment.recruitment')),
                    ],
                    options={'ordering': ['-created_at']},
                ),
                migrations.CreateModel(
                    name='RecruitmentApproval',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                        ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sequence')),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval Status')),
                        ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                        ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                        ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_approvals', to='employee.employee', verbose_name='Approver')),
                        ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                        ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                        ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='recruitment.recruitment', verbose_name='Recruitment')),
                    ],
                    options={'verbose_name': 'Recruitment Approval', 'verbose_name_plural': 'Recruitment Approvals', 'ordering': ['sequence']},
                ),
                # Recruitment fields already in production
                migrations.AddField(model_name='recruitment', name='approval_status', field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval Status')),
                migrations.AddField(model_name='recruitment', name='bayt_external_id', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='recruitment', name='bayt_posted_at', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='recruitment', name='hr_feedback', field=models.TextField(blank=True, null=True, verbose_name='HR Feedback')),
                migrations.AddField(model_name='recruitment', name='linkedin_external_id', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='recruitment', name='linkedin_posted_at', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='recruitment', name='naukrigulf_external_id', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='recruitment', name='naukrigulf_posted_at', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='recruitment', name='published_to_bayt', field=models.BooleanField(default=False)),
                migrations.AddField(model_name='recruitment', name='published_to_linkedin', field=models.BooleanField(default=False)),
                migrations.AddField(model_name='recruitment', name='published_to_naukrigulf', field=models.BooleanField(default=False)),
                migrations.AddField(model_name='recruitment', name='raised_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_recruitments', to='employee.employee', verbose_name='Raised By')),
                migrations.AddField(model_name='recruitment', name='raised_from_employee', field=models.BooleanField(default=False, verbose_name='Raised from Employee')),
                # LinkedInAccount.organization_id already in production
                migrations.AddField(model_name='linkedinaccount', name='organization_id', field=models.CharField(blank=True, help_text='Numeric LinkedIn company page ID. When set, posts go to the company page instead of personal feed.', max_length=250, null=True, verbose_name='LinkedIn Organization ID')),
                # AlterField for source + is_published (safe to re-state even if already done)
                migrations.AlterField(model_name='candidate', name='source', field=models.CharField(blank=True, choices=[('application', 'Application Form'), ('software', 'Inside software'), ('linkedin', 'LinkedIn'), ('bayt', 'Bayt.com'), ('naukrigulf', 'NaukriGulf'), ('other', 'Other')], max_length=20, null=True, verbose_name='Source')),
                migrations.AlterField(model_name='historicalcandidate', name='source', field=models.CharField(blank=True, choices=[('application', 'Application Form'), ('software', 'Inside software'), ('linkedin', 'LinkedIn'), ('bayt', 'Bayt.com'), ('naukrigulf', 'NaukriGulf'), ('other', 'Other')], max_length=20, null=True, verbose_name='Source')),
                migrations.AlterField(model_name='recruitment', name='is_published', field=models.BooleanField(default=False, help_text='To publish a recruitment in website, if false then it             will not appear on open recruitment page.', verbose_name='Is Published')),
            ],
            database_operations=[],  # All these already exist in production — skip DDL
        ),

        # ── OfferLetterTemplate — table created by 0001 with old columns ────────
        # On a fresh DB, 0001_candidate_perf_indexes creates this table with
        # columns (content, is_default). We update only Django's state here and
        # rename those columns in the database if they still have the old names.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='OfferLetterTemplate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                        ('body_html', models.TextField(help_text='Use {{candidate_name}}, {{position}}, {{department}}, {{joining_date}}, {{basic_salary}}, {{company_name}} as placeholders', verbose_name='Body HTML')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={'verbose_name': 'Offer Letter Template', 'verbose_name_plural': 'Offer Letter Templates', 'ordering': ['name']},
                ),
            ],
            database_operations=[
                # Rename old columns to new names if the table was created by 0001 with old schema.
                # Uses DO $$ to make each rename idempotent (safe on both fresh and existing DBs).
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_name = 'recruitment_offerlettertemplate'
                                  AND column_name = 'content'
                            ) THEN
                                ALTER TABLE recruitment_offerlettertemplate
                                    RENAME COLUMN content TO body_html;
                            END IF;
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_name = 'recruitment_offerlettertemplate'
                                  AND column_name = 'is_default'
                            ) THEN
                                ALTER TABLE recruitment_offerlettertemplate
                                    RENAME COLUMN is_default TO is_active;
                            END IF;
                        END
                        $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.CreateModel(
            name='OfferLetterApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Sequence')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback / Rejection Reason')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Acted At')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter_approvals', to='employee.employee', verbose_name='Approver')),
                ('offer_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='recruitment.offerletter', verbose_name='Offer Letter')),
            ],
            options={'verbose_name': 'Offer Letter Approval', 'verbose_name_plural': 'Offer Letter Approvals', 'ordering': ['sequence']},
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Round Number')),
                ('label', models.CharField(default='', max_length=100, verbose_name='Label')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='recruitment.interviewschedule', verbose_name='Interview')),
            ],
            options={'verbose_name': 'Interview Round', 'verbose_name_plural': 'Interview Rounds', 'ordering': ['round_number']},
        ),
        # ── CandidateScreeningProfile — also created by 0001, skip DDL ──────────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CandidateScreeningProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('extracted_skills', models.JSONField(blank=True, default=list)),
                        ('years_experience', models.IntegerField(default=0)),
                        ('education', models.JSONField(blank=True, default=list)),
                        ('previous_positions', models.JSONField(blank=True, default=list)),
                        ('matching_score', models.IntegerField(default=0)),
                        ('matching_skills', models.JSONField(blank=True, default=list)),
                        ('missing_skills', models.JSONField(blank=True, default=list)),
                        ('summary', models.TextField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                        ('recommendation', models.CharField(blank=True, choices=[('auto_shortlist', 'Auto-Shortlist'), ('interview', 'Interview'), ('reject', 'Reject')], max_length=100, null=True)),
                        ('screened_at', models.DateTimeField(auto_now_add=True)),
                        ('ai_model', models.CharField(blank=True, max_length=100, null=True)),
                        ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_profile', to='recruitment.candidate')),
                        ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                    ],
                ),
            ],
            database_operations=[],  # Table already created by 0001_candidate_perf_indexes
        ),

        # ── New columns on Candidate (don't exist yet) ────────────────────────
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='recruitment/candidate/cover_letter/%Y/', verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='graduation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='recruitment/candidate/certificates/%Y/', verbose_name='Graduation Certificate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='promoted_to_onboarding',
            field=models.BooleanField(default=False, verbose_name='Promoted to Onboarding'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='transcripts',
            field=models.FileField(blank=True, null=True, upload_to='recruitment/candidate/transcripts/%Y/', verbose_name='Transcripts'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='cover_letter',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Cover Letter'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='graduation_certificate',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Graduation Certificate'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='promoted_to_onboarding',
            field=models.BooleanField(default=False, verbose_name='Promoted to Onboarding'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='transcripts',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Transcripts'),
        ),
    ]
