# Generated by Django 4.2.23 on 2026-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_jobemailtemplate_offerlettertemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Interview Time'),
        ),
    ]
