# Generated by Django 4.2.23 on 2026-05-13 18:16
# All tables, columns, and indexes this migration was meant to create or add
# are already present after 0001_candidate_perf_indexes (on a fresh DB) or
# were applied directly on production before migrations were introduced.
# This migration is intentionally a no-op to preserve the dependency chain.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_candidate_perf_indexes'),
        ('recruitment', '0007_seed_offer_letter_templates'),
    ]

    operations = []
