# Generated by Django 4.2.23 on 2026-05-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_offerapproval_offerletter_approval_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='num_rounds',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Rounds'),
        ),
    ]
