# Generated by Django 4.2.23 on 2026-05-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_add_num_rounds_to_interviewschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletterapproval',
            name='signature_image',
            field=models.TextField(blank=True, verbose_name='Signature (base64)'),
        ),
    ]
