# Generated by Django 4.2.23 on 2026-05-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_candidate_perf_indexes'),
        ('recruitment', '0010_add_signature_image_to_offerletterapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('body_html', models.TextField(help_text='Use {{candidate_name}}, {{position}}, {{company_name}} as placeholders', verbose_name='Body HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medical Letter Template',
                'verbose_name_plural': 'Medical Letter Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisaLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('body_html', models.TextField(help_text='Use {{candidate_name}}, {{position}}, {{company_name}} as placeholders', verbose_name='Body HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visa Letter Template',
                'verbose_name_plural': 'Visa Letter Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='offerapproval',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_approvals', to='recruitment.offerletter', verbose_name='Offer Letter'),
        ),
        migrations.CreateModel(
            name='VisaLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Letter Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('hr_signed', models.BooleanField(default=False)),
                ('hr_signature', models.TextField(blank=True, verbose_name='HR Signature (base64)')),
                ('hr_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_letter', to='recruitment.candidate', verbose_name='Candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_letters_created', to='employee.employee', verbose_name='Created By')),
                ('hr_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_letters_signed', to='employee.employee', verbose_name='Signed By')),
            ],
            options={
                'verbose_name': 'Visa Letter',
                'verbose_name_plural': 'Visa Letters',
            },
        ),
        migrations.CreateModel(
            name='MedicalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Letter Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('hr_signed', models.BooleanField(default=False)),
                ('hr_signature', models.TextField(blank=True, verbose_name='HR Signature (base64)')),
                ('hr_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_letter', to='recruitment.candidate', verbose_name='Candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_letters_created', to='employee.employee', verbose_name='Created By')),
                ('hr_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_letters_signed', to='employee.employee', verbose_name='Signed By')),
            ],
            options={
                'verbose_name': 'Medical Letter',
                'verbose_name_plural': 'Medical Letters',
            },
        ),
    ]
