# Generated by Django 4.2.23 on 2026-05-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_candidate_project_fk'),
        ('recruitment', '0010_add_signature_image_to_offerletterapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='project_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='offerapproval',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_approvals', to='recruitment.offerletter', verbose_name='Offer Letter'),
        ),
    ]
