# Generated by Django 4.2.23 on 2026-05-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_candidate_project_fk'),
        ('recruitment', '0013_module9_doc_tracking'),
    ]

    operations = [
    ]
