# Generated by Django 4.2.23 on 2026-05-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_merge_20260516_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapproval',
            name='signature_image',
            field=models.TextField(blank=True, verbose_name='Signature (base64)'),
        ),
        migrations.AlterField(
            model_name='medicalletterstatuslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerletterstatuslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visaletterstatuslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
