# Generated by Django 4.2.23 on 2026-05-21 14:25

from django.db import migrations, models
import recruitment.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0027_jobapplication_skills_rejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateportalupload',
            name='file',
            field=models.FileField(upload_to=recruitment.models._portal_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='candidateportalupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidateportalupload',
            name='label',
            field=models.CharField(blank=True, help_text="Optional custom label, e.g. 'MSc Degree 2022'", max_length=100, verbose_name='Label'),
        ),
    ]
