# Generated by Django 4.2.23 on 2026-05-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0028_alter_candidateportalupload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_driving_license',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_experience_local_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_experience_overseas_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_lang_arabic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_lang_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_lang_others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_place_of_birth',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_present_employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_qualification_academic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='extracted_qualification_professional',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
