# Generated by Django 4.2.23 on 2026-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0030_recruitmentapproval_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='ai_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='oneic_grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='oneic_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidatescreeningprofile',
            name='scoring_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
