# Generated by Django 4.2.23 on 2026-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0034_add_round_number_to_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Work Location'),
        ),
    ]
