# Generated by Django 4.2.23 on 2026-06-11 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mailbox_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0036_onboardingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='is_bulk',
            field=models.BooleanField(default=False, help_text='True for the umbrella request that groups several positions under a single approval. On approval it fans out into one published campaign per BulkRequestLine.', verbose_name='Bulk Request'),
        ),
        migrations.CreateModel(
            name='BulkRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=120, verbose_name='Position / Title')),
                ('vacancy', models.PositiveIntegerField(default=1, verbose_name='Vacancies')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('job_position', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_request_lines', to='base.jobposition', verbose_name='Job Position')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('published_recruitment', models.ForeignKey(blank=True, help_text='The campaign spawned for this line once the bulk request is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_source_line', to='recruitment.recruitment', verbose_name='Published Campaign')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_lines', to='recruitment.recruitment', verbose_name='Bulk Request')),
            ],
            options={
                'verbose_name': 'Bulk Request Line',
                'verbose_name_plural': 'Bulk Request Lines',
                'ordering': ['id'],
            },
        ),
    ]
