# Generated by Django 4.2.23 on 2026-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0037_recruitment_is_bulk_bulkrequestline'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletterapproval',
            name='esign_provider',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='E-Sign Provider'),
        ),
        migrations.AddField(
            model_name='offerletterapproval',
            name='esign_reference',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='E-Sign Reference'),
        ),
        migrations.AddField(
            model_name='proposalapproval',
            name='esign_provider',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='E-Sign Provider'),
        ),
        migrations.AddField(
            model_name='proposalapproval',
            name='esign_reference',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='E-Sign Reference'),
        ),
    ]
