# Generated by Django 4.2.23 on 2026-10-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_docusignaccount_adobesignaccount'),
        ('employee', '0001_candidate_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('OMR', 'Omani Rial'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='OMR', max_length=3, verbose_name='Currency')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Exchange Rate')),
                ('local_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Local Amount (OMR)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20, verbose_name='Status')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Submitted Date')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('approved_by_finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approved_expense_claims', to='employee.employee')),
                ('approved_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expense_claims', to='employee.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Expense Claim',
                'verbose_name_plural': 'Expense Claims',
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period_start', models.DateField(verbose_name='Report Period Start')),
                ('report_period_end', models.DateField(verbose_name='Report Period End')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20, verbose_name='Status')),
                ('submitted_date', models.DateTimeField(blank=True, null=True, verbose_name='Submitted Date')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approved Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Expense Report',
                'verbose_name_plural': 'Expense Reports',
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(choices=[('business', 'Business Travel'), ('training', 'Training'), ('conference', 'Conference'), ('client_visit', 'Client Visit')], max_length=20, verbose_name='Travel Type')),
                ('purpose', models.TextField(verbose_name='Purpose of Travel')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('return_date', models.DateField(verbose_name='Return Date')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Estimated Cost')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Submitted Date')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('approved_by_finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approved_travel_requests', to='employee.employee')),
                ('approved_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_travel_requests', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Travel Request',
                'verbose_name_plural': 'Travel Requests',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(upload_to='expenses/receipts/', verbose_name='Receipt File')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('receipt_date', models.DateField(verbose_name='Receipt Date')),
                ('ocr_extracted_data', models.JSONField(blank=True, null=True, verbose_name='OCR Extracted Data')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('expense_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenseclaim')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.CreateModel(
            name='ExpensePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=200, verbose_name='Policy Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Amount')),
                ('requires_receipt', models.BooleanField(default=True, verbose_name='Requires Receipt')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requires Approval')),
                ('approval_levels', models.PositiveIntegerField(default=1, verbose_name='Approval Levels')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'verbose_name': 'Expense Policy',
                'verbose_name_plural': 'Expense Policies',
            },
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='travel_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.travelrequest'),
        ),
        migrations.CreateModel(
            name='PerDiemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate Amount')),
                ('currency', models.CharField(choices=[('OMR', 'Omani Rial'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='OMR', max_length=3, verbose_name='Currency')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'verbose_name': 'Per Diem Rate',
                'verbose_name_plural': 'Per Diem Rates',
                'unique_together': {('country', 'city', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenseclaim')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensereport')),
            ],
            options={
                'verbose_name': 'Expense Report Item',
                'verbose_name_plural': 'Expense Report Items',
                'unique_together': {('expense_report', 'expense_claim')},
            },
        ),
    ]
