# Generated by Django 4.2.23 on 2026-10-03 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_docusignaccount_adobesignaccount'),
        ('employee', '0001_candidate_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmaniTaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('month', models.DateField(verbose_name='Month')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Salary')),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxable Income')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax Amount')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax Rate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Omani Tax Calculation',
                'verbose_name_plural': 'Omani Tax Calculations',
            },
        ),
        migrations.CreateModel(
            name='OmaniLabourLawConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('annual_leave_days', models.IntegerField(default=30, verbose_name='Annual Leave Days')),
                ('sick_leave_full_pay_days', models.IntegerField(default=10, verbose_name='Sick Leave Full Pay Days')),
                ('sick_leave_half_pay_days', models.IntegerField(default=10, verbose_name='Sick Leave Half Pay Days')),
                ('sick_leave_unpaid_days', models.IntegerField(default=10, verbose_name='Sick Leave Unpaid Days')),
                ('maternity_leave_days', models.IntegerField(default=50, verbose_name='Maternity Leave Days')),
                ('hajj_leave_days', models.IntegerField(default=15, verbose_name='Hajj Leave Days')),
                ('emergency_leave_days', models.IntegerField(default=6, verbose_name='Emergency Leave Days')),
                ('daily_working_hours', models.IntegerField(default=8, verbose_name='Daily Working Hours')),
                ('weekly_working_hours', models.IntegerField(default=45, verbose_name='Weekly Working Hours')),
                ('overtime_regular_rate', models.DecimalField(decimal_places=2, default=1.25, max_digits=5, verbose_name='Regular Overtime Rate')),
                ('overtime_holiday_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Holiday Overtime Rate')),
                ('gratuity_days_per_year', models.IntegerField(default=15, verbose_name='Gratuity Days Per Year')),
                ('probation_period_months', models.IntegerField(default=3, verbose_name='Probation Period (Months)')),
                ('pasi_enabled', models.BooleanField(default=False, verbose_name='PASI Integration Enabled')),
                ('pasi_employee_rate', models.DecimalField(decimal_places=2, default=0.105, max_digits=5, verbose_name='PASI Employee Rate')),
                ('pasi_employer_rate', models.DecimalField(decimal_places=2, default=0.125, max_digits=5, verbose_name='PASI Employer Rate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Omani Labour Law Configuration',
                'verbose_name_plural': 'Omani Labour Law Configurations',
            },
        ),
        migrations.CreateModel(
            name='OmaniComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('check_type', models.CharField(max_length=100, verbose_name='Check Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('warning', 'Warning')], max_length=20, verbose_name='Status')),
                ('details', models.JSONField(default=dict, verbose_name='Details')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Omani Compliance Audit',
                'verbose_name_plural': 'Omani Compliance Audits',
            },
        ),
    ]
