# Generated by Django 4.2.23 on 2026-10-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_docusignaccount_adobesignaccount'),
        ('employee', '0001_candidate_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200, verbose_name='Role Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('criticality_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, verbose_name='Criticality Level')),
                ('vacancy_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, verbose_name='Vacancy Risk')),
                ('succession_required', models.BooleanField(default=True, verbose_name='Succession Required')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobposition')),
            ],
            options={
                'verbose_name': 'Critical Role',
                'verbose_name_plural': 'Critical Roles',
            },
        ),
        migrations.CreateModel(
            name='TalentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Review Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('review_date', models.DateField(verbose_name='Review Date')),
                ('outcomes', models.TextField(blank=True, verbose_name='Outcomes')),
                ('action_items', models.TextField(blank=True, verbose_name='Action Items')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Next Review Date')),
                ('facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_talent_reviews', to='employee.employee')),
                ('participants', models.ManyToManyField(related_name='talent_reviews_participated', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Talent Review',
                'verbose_name_plural': 'Talent Reviews',
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('exceptional', 'Exceptional')], max_length=20, verbose_name='Performance Level')),
                ('potential_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('exceptional', 'Exceptional')], max_length=20, verbose_name='Potential Level')),
                ('career_aspirations', models.TextField(blank=True, verbose_name='Career Aspirations')),
                ('mobility_willingness', models.BooleanField(default=False, verbose_name='Willing to Relocate')),
                ('readiness_level', models.CharField(choices=[('ready_now', 'Ready Now'), ('ready_1_2_years', 'Ready in 1-2 Years'), ('ready_3plus_years', 'Ready in 3+ Years'), ('not_ready', 'Not Ready')], max_length=20, verbose_name='Readiness Level')),
                ('development_needs', models.TextField(blank=True, verbose_name='Development Needs')),
                ('last_assessment_date', models.DateField(verbose_name='Last Assessment Date')),
                ('next_assessment_date', models.DateField(verbose_name='Next Assessment Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Talent Profile',
                'verbose_name_plural': 'Talent Profiles',
            },
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('exceptional', 'Exceptional')], max_length=20, verbose_name='Readiness Level')),
                ('estimated_timeline_months', models.PositiveIntegerField(verbose_name='Estimated Timeline (Months)')),
                ('development_plan', models.TextField(verbose_name='Development Plan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='draft', max_length=20, verbose_name='Status')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('critical_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.criticalrole')),
                ('primary_successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_successor_for', to='employee.employee')),
                ('secondary_successor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_successor_for', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Succession Plan',
                'verbose_name_plural': 'Succession Plans',
            },
        ),
        migrations.CreateModel(
            name='RetentionRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, verbose_name='Risk Level')),
                ('risk_factors', models.TextField(verbose_name='Risk Factors')),
                ('mitigation_strategy', models.TextField(blank=True, verbose_name='Mitigation Strategy')),
                ('assessed_date', models.DateField(verbose_name='Assessed Date')),
                ('next_assessment_date', models.DateField(verbose_name='Next Assessment Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Retention Risk',
                'verbose_name_plural': 'Retention Risks',
            },
        ),
        migrations.CreateModel(
            name='NineBoxMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Performance Score')),
                ('potential_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Potential Score')),
                ('assessment_date', models.DateField(verbose_name='Assessment Date')),
                ('quadrant', models.CharField(choices=[('underperformer', 'Underperformer'), ('core_player', 'Core Player'), ('growth_star', 'Growth Star'), ('top_talent', 'Top Talent'), ('effective_specialist', 'Effective Specialist')], max_length=20, verbose_name='Quadrant')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_nine_boxes', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': '9-Box Matrix Assessment',
                'verbose_name_plural': '9-Box Matrix Assessments',
            },
        ),
        migrations.CreateModel(
            name='LeadershipPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadership_level', models.CharField(choices=[('emerging_leader', 'Emerging Leader'), ('team_leader', 'Team Leader'), ('department_head', 'Department Head'), ('executive', 'Executive')], max_length=50, verbose_name='Leadership Level')),
                ('target_level', models.CharField(choices=[('team_leader', 'Team Leader'), ('department_head', 'Department Head'), ('executive', 'Executive'), ('senior_executive', 'Senior Executive')], max_length=50, verbose_name='Target Level')),
                ('development_plan', models.TextField(verbose_name='Development Plan')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Progress %')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_leaders', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Leadership Pipeline',
                'verbose_name_plural': 'Leadership Pipelines',
            },
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_months', models.PositiveIntegerField(verbose_name='Timeline (Months)')),
                ('development_activities', models.TextField(verbose_name='Development Activities')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('target_completion_date', models.DateField(verbose_name='Target Completion Date')),
                ('current_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_positions', to='base.jobposition')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('target_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_positions', to='base.jobposition')),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
            },
        ),
    ]
