# Generated by Django 4.2.23 on 2026-10-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_docusignaccount_adobesignaccount'),
        ('employee', '0001_candidate_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Certification Name')),
                ('issuing_authority', models.CharField(max_length=100, verbose_name='Issuing Authority')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('validity_period_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Validity Period (Months)')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Plan Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_plans', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Learning Plan',
                'verbose_name_plural': 'Learning Plans',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('format', models.CharField(choices=[('online', 'Online'), ('classroom', 'Classroom'), ('blended', 'Blended'), ('self-paced', 'Self-Paced')], max_length=20, verbose_name='Format')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, verbose_name='Level')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='Duration (Hours)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('instructor', models.CharField(blank=True, max_length=100, verbose_name='Instructor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.coursecategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'verbose_name': 'Training Course',
                'verbose_name_plural': 'Training Courses',
            },
        ),
        migrations.CreateModel(
            name='LearningPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('target_date', models.DateField(verbose_name='Target Date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.trainingcourse')),
                ('learning_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningplan')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
            ],
            options={
                'verbose_name': 'Learning Plan Item',
                'verbose_name_plural': 'Learning Plan Items',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Certificate Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.certification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Certification',
                'verbose_name_plural': 'Employee Certifications',
            },
        ),
        migrations.CreateModel(
            name='TrainingBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget Amount')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Allocated Amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remaining Amount')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
            ],
            options={
                'verbose_name': 'Training Budget',
                'verbose_name_plural': 'Training Budgets',
                'unique_together': {('department', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, verbose_name='Proficiency Level')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('last_used', models.DateField(blank=True, null=True, verbose_name='Last Used')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='Verification Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_skills', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Enrollment Date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Progress %')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Final Score')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Certificate Issued')),
                ('certificate_issue_date', models.DateField(blank=True, null=True, verbose_name='Certificate Issue Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.trainingcourse')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'unique_together': {('employee', 'course')},
            },
        ),
    ]
