# Generated by Django 4.2.23 on 2026-06-11 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_mailbox_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocusignAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('base_uri', models.CharField(blank=True, help_text='Per-account REST base URI returned by DocuSign userinfo', max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docusign_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DocuSign Account',
                'verbose_name_plural': 'DocuSign Accounts',
            },
        ),
        migrations.CreateModel(
            name='AdobeSignAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_access_point', models.CharField(blank=True, help_text='Per-account API base returned by Adobe baseUris', max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adobesign_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adobe Sign Account',
                'verbose_name_plural': 'Adobe Sign Accounts',
            },
        ),
    ]
