"""
Django settings for FITS HCMS project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import importlib.util
from os.path import join
from pathlib import Path
from dotenv import load_dotenv
import environ
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(
        str,
        "django-insecure-j8op9)1q8$1&0^s&p*_0%d#pr@w9qj@1o=3#@d=a(^@9@zd@%j",
    ),
    ALLOWED_HOSTS=(list, ["*"]),
    CSRF_TRUSTED_ORIGINS=(list, ["http://localhost:8000"]),
    TRIAL_MODE=(bool, False),
    TRIAL_START_DATE=(str, ""),
    TRIAL_DURATION_DAYS=(int, 30),
    TRIAL_DEMO_DATA_FIXTURE=(str, "django_data.json"),
)

env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "notifications",
    "mathfilters",
    "corsheaders",
    "simple_history",
    "django_filters",
    "fits_audit",
    "accessibility",
    "fits_documents",
    "sitewide_chatbot",
    "project",
    "attendance",
    "leave",
    "base",
    "employee",
    "recruitment",
    "ui",
    "widget_tweaks",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "base.middleware.TrialAccessMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fits.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "fits.config.get_MENUS",
                "base.context_processors.get_companies",
                "base.context_processors.white_labelling_company",
                "base.context_processors.resignation_request_enabled",
                "base.context_processors.timerunner_enabled",
                "base.context_processors.intial_notice_period",
                "base.context_processors.check_candidate_self_tracking",
                "base.context_processors.check_candidate_self_tracking_rating",
                "base.context_processors.get_initial_prefix",
                "base.context_processors.biometric_app_exists",
                "base.context_processors.enable_late_come_early_out_tracking",
                "base.context_processors.enable_profile_edit",
            ],
        },
    },
]

WSGI_APPLICATION = "fits.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DEFAULT_DB_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://postgres.iaahzdewzqzkrcqacosn:06nO7j8ENcpvI9vJ@aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres"
)

DATABASES = {
    "default": env.db("DATABASE_URL", default=DEFAULT_DB_URL),
}

if DATABASES["default"]["ENGINE"] != "django.db.backends.sqlite3":
    is_serverless = bool(os.environ.get("VERCEL") or os.environ.get("AWS_LAMBDA_FUNCTION_NAME"))
    DATABASES["default"]["CONN_MAX_AGE"] = 0 if is_serverless else 600
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True
    DATABASES["default"]["OPTIONS"] = {"connect_timeout": 10}

# Add caching for dramatic performance improvements
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "fits-cache",
        "TIMEOUT": 300,  # 5 minutes default cache
        "OPTIONS": {"MAX_ENTRIES": 10000},
    }
}

# Cache form renderings and querysets
CACHE_FORM_QUERYSETS = True
CACHE_TIMEOUT_SECONDS = 300

# Use cached_db sessions: reads from in-memory cache (fast), falls back to DB
# Dramatically speeds up session lookup for logged-in users
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# Enable persistent database connections
DATABASE_CONN_MAX_AGE = 600

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MESSAGE_TAGS = {
    messages.DEBUG: "oh-alert--warning",
    messages.INFO: "oh-alert--info",
    messages.SUCCESS: "oh-alert--success",
    messages.WARNING: "oh-alert--warning",
    messages.ERROR: "oh-alert--danger",
}


CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")

TRIAL_MODE = env("TRIAL_MODE")
TRIAL_START_DATE = env("TRIAL_START_DATE")
TRIAL_DURATION_DAYS = env("TRIAL_DURATION_DAYS")
TRIAL_DEMO_DATA_FIXTURE = env("TRIAL_DEMO_DATA_FIXTURE")

# Email Configuration (Brevo SMTP)
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp-relay.brevo.com")
EMAIL_PORT = env("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@example.com")

# Recipient for "Send to Visa Department" onboarding hand-off + portal link base URL
VISA_TEAM_EMAIL = env("VISA_TEAM_EMAIL", default="")
SITE_URL = env("SITE_URL", default="https://hcmspro.net")

# Gmail OAuth (Profile -> Integrations -> Connect Gmail)
GMAIL_CLIENT_ID = env("GMAIL_CLIENT_ID", default="")
GMAIL_CLIENT_SECRET = env("GMAIL_CLIENT_SECRET", default="")
GMAIL_REDIRECT_URI = env(
    "GMAIL_REDIRECT_URI",
    default="http://localhost:8000/integrations/gmail/callback/",
)

# DocuSign eSignature OAuth (Integrations -> Connect DocuSign). Sandbox defaults.
DOCUSIGN_CLIENT_ID = env("DOCUSIGN_CLIENT_ID", default="")
DOCUSIGN_SECRET = env("DOCUSIGN_SECRET", default="")
DOCUSIGN_ACCOUNT_ID = env("DOCUSIGN_ACCOUNT_ID", default="")
DOCUSIGN_OAUTH_BASE = env("DOCUSIGN_OAUTH_BASE", default="https://account-d.docusign.com")
DOCUSIGN_REDIRECT_URI = env(
    "DOCUSIGN_REDIRECT_URI",
    default="http://localhost:8000/integrations/docusign/callback/",
)

# Adobe Acrobat Sign OAuth (Integrations -> Connect Adobe eSign).
ADOBE_SIGN_CLIENT_ID = env("ADOBE_SIGN_CLIENT_ID", default="")
ADOBE_SIGN_SECRET = env("ADOBE_SIGN_SECRET", default="")
ADOBE_SIGN_OAUTH_BASE = env("ADOBE_SIGN_OAUTH_BASE", default="https://secure.na1.adobesign.com")
ADOBE_SIGN_REDIRECT_URI = env(
    "ADOBE_SIGN_REDIRECT_URI",
    default="http://localhost:8000/integrations/adobesign/callback/",
)

LOGIN_URL = "/ui/login/"
LOGIN_REDIRECT_URL = "/ui/dashboard/"


SIMPLE_HISTORY_REVERT_DISABLED = True


DJANGO_NOTIFICATIONS_CONFIG = {
    "USE_JSONFIELD": True,
    "SOFT_DELETE": True,
    "USE_WATCHED": True,
    "NOTIFICATIONS_STORAGE": "notifications.storage.DatabaseStorage",
    "TEMPLATE": "notifications.html",  # Add this line
}

X_FRAME_OPTIONS = "SAMEORIGIN"

LANGUAGES = (
    ("en", "English (US)"),
    ("de", "Deutsche"),
    ("es", "Español"),
    ("fr", "Français"),
    ("ar", "عربى"),
    ("pt-br", "Português (Brasil)"),
    ("zh-hans", "Simplified Chinese"),
    ("zh-hant", "Traditional Chinese"),
    ("it", "Italian"),
)


LOCALE_PATHS = [
    join(BASE_DIR, "fits", "locale"),
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE", default="Asia/Kolkata")

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Production settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_SSL_REDIRECT = not bool(os.environ.get("VERCEL"))
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")



load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "dummy-key")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")