from django.urls import path
from ui import views, views_esign

app_name = "ui"

urlpatterns = [
    path("esign/<str:provider>/<str:kind>/<int:obj_id>/start/",
         views_esign.esign_start, name="esign-start"),
    path("esign/<str:provider>/<str:kind>/<int:obj_id>/pick/",
         views_esign.esign_pick, name="esign-pick"),
    path("esign/<str:provider>/<str:kind>/<int:obj_id>/return/<int:approval_id>/",
         views_esign.esign_return, name="esign-return"),
    path("dashboard/",                     views.dashboard,                  name="dashboard"),
    path("dashboard/calendar-events/",     views.dashboard_calendar_events,  name="dashboard-calendar-events"),
    path("candidates/",        views.candidates,         name="candidates"),
    path("job-requisition/",   views.job_requisition,    name="job-requisition"),
    path("jd-creator/",        views.jd_creator,         name="jd-creator"),
    path("approvals/",         views.approvals,          name="approvals"),
    path("manpower-request/",  views.manpower_request,   name="manpower-request"),
    path("bulk-request/",      views.bulk_request,       name="bulk-request"),
    path("manpower-approval/", views.manpower_approval,  name="manpower-approval"),
    path("manpower-approval/<int:rec_id>/", views.manpower_approval, name="manpower-approval-detail"),
    path("interview/",         views.interview,           name="interview"),
    path("interview-creator/", views.interview_creator,  name="interview-creator"),
    path("offers/",            views.offers,             name="offers"),
    path("offer-creator/",     views.offer_creator,      name="offer-creator"),
    path("profile/",           views.profile,            name="profile"),
    path("notifications/",     views.notifications,      name="notifications"),
    path("settings/",          views.settings_page,      name="settings"),
    path("integrations/",      views.integrations,       name="integrations"),
    path("login/",             views.login_view,         name="login"),
    path("candidate-create/",  views.candidate_create,   name="candidate-create"),
    path("jd-generate/",       views.jd_generate,        name="jd-generate"),
    path("candidate/<int:cand_id>/",        views.candidate_detail,  name="candidate-detail"),
    path("candidate/<int:cand_id>/screen/",        views.candidate_screen,        name="candidate-screen"),
    path("candidate/<int:cand_id>/screen-status/", views.candidate_screen_status, name="candidate-screen-status"),
    path("candidates/kpi/",                        views.candidates_kpi,          name="candidates-kpi"),
    path("candidate/<int:cand_id>/promote/",      views.candidate_promote,      name="candidate-promote"),
    path("candidate/<int:cand_id>/reject/",       views.candidate_reject,       name="candidate-reject"),
    path("candidate/<int:cand_id>/hr-override/",  views.candidate_hr_override,  name="candidate-hr-override"),
    path("candidate/<int:cand_id>/delete/",  views.candidate_delete,  name="candidate-delete"),
    path("interview/<int:iv_id>/edit/",      views.interview_edit,    name="interview-edit"),
    path("interview/<int:iv_id>/delete/",    views.interview_delete,  name="interview-delete"),
    path("interview/<int:iv_id>/evaluate/",  views.interview_evaluate, name="interview-evaluate"),
    path("offer/<int:offer_id>/",                      views.offer_detail,        name="offer-detail"),
    path("offer/<int:offer_id>/esign/",               views.offer_esign,         name="offer-esign"),
    path("offer/<int:offer_id>/setup-chain/",         views.offer_setup_chain,   name="offer-setup-chain"),
    path("offer/<int:offer_id>/download/letter/",     views.offer_download_letter,     name="offer-download-letter"),
    path("offer/<int:offer_id>/download/ctc/",        views.offer_download_ctc,        name="offer-download-ctc"),
    path("offer/<int:offer_id>/download/policy/",     views.offer_download_policy,     name="offer-download-policy"),
    path("offer/<int:offer_id>/download/terms/",      views.offer_download_terms,      name="offer-download-terms"),
    path("proposals/",                       views.proposal_list,     name="proposal-list"),
    path("proposal/<int:proposal_id>/",      views.proposal_detail,   name="proposal-detail"),
    path("recruitment/<int:rec_id>/feedback/", views.recruitment_feedback, name="recruitment-feedback"),
    path("recruitment/<int:rec_id>/publish/<str:channel>/", views.recruitment_publish, name="recruitment-publish"),
    path("offer/<int:offer_id>/letter-approval/", views.offer_letter_approval, name="offer-letter-approval"),
    path("proposal-creator/",                   views.proposal_creator,      name="proposal-creator"),
    path("offer-letter-template/",              views.offer_letter_template, name="offer-letter-template"),
    path("report-analysis/",                    views.report_analysis,       name="report-analysis"),
    path("interview/<int:iv_id>/final-eval/",   views.interview_final_eval,  name="interview-final-eval"),
    path("offer/<int:offer_id>/final-review/",  views.offer_final_review,    name="offer-final-review"),
    path("approval-rules/",                     views.approval_rules,        name="approval-rules"),
    # ── Proposal Creator & Approval ─────────────────────────────────────────
    path("proposal-creator/",                    views.proposal_creator,           name="proposal-creator"),
    path("offer/<int:offer_id>/approval/",       views.offer_approval,             name="offer-approval"),
    # ── New pages (from Figma) ───────────────────────────────────────────────
    path("candidate/<int:cand_id>/documents/",   views.candidate_documents,        name="candidate-documents"),
    path("candidate-pipeline/",                  views.candidate_pipeline,         name="candidate-pipeline"),
    path("candidate/<int:cand_id>/interviews/",  views.candidate_interview_view,   name="candidate-interview-view"),
    path("candidate/<int:cand_id>/communication/", views.candidate_communication,  name="candidate-communication"),
    path("candidate/<int:cand_id>/offer-view/",  views.candidate_offer_view,       name="candidate-offer-view"),
    path("candidate/<int:cand_id>/offer/",       views.candidate_offer_view,       name="candidate-offer"),
    path("candidate/<int:cand_id>/profile/",     views.candidate_profile_view,     name="candidate-profile-view"),
    path("offer-letter-templates/",              views.offer_letter_template_view, name="offer-letter-template"),
    path("proposal/<int:proposal_id>/approval/", views.proposal_approval_view,     name="proposal-approval"),
    path("offer/<int:offer_id>/letter-approval/", views.offer_letter_approval_view, name="offer-letter-approval"),
    # ── Employment Proposal Form (Job Requisition) ───────────────────────────
    path("employment-proposal/",                  views.employment_proposal_form,   name="employment-proposal"),
    # ── Offer Creator API ────────────────────────────────────────────────────
    path("api/proposal-autofill/<int:candidate_id>/", views.api_proposal_autofill, name="api-proposal-autofill"),
]
