# Generated by Django 4.2.23 on 2026-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_candidate_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceGeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_runner', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendancelatecomeearlyout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gracetime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
